### ISSUE TITLE
Convert from Guest to Logged-in User

### ISSUE THREAD

**Issue by messamer** [radiasoft/sirepo#1687]
If someone begins as a Guest user, they should be able to convert to a Logged-in user and move over any simulations they have created.

**Comment by robnagler** [comment]
Yes, this is how it works. You simply login with Email or GitHub, depending on how the system is configured.

**Comment by messamer** [comment]
I showed this to Paul before opening the issue.  

Once you sign-in as guest by providing a full name,  there is not an option for GitHub or Email under the person silhouette icon on the top right corner of the window.

**Comment by pmessamer** [comment]
![950600B9-D082-40ED-8902-B239E2B0DE31](https://user-images.githubusercontent.com/945686/58370265-c75c1780-7ec1-11e9-8bc2-1bed9f5414aa.png)

**Comment by messamer** [comment]
Here is the scenario I am concerned about:  The user comes to Sirepo and accesses as guest providing a full name: "Josh Anderson".  They spend some time developing a simulation and decide that they want to sign-in so they don't lose their work (regardless of whether their work would disappear, this is about managing the expectations of the user).  From the interface now, I don't see a way for the user to convert from a guest to a logged-in user.  In addition, the fact that the system is using the name they provided rather than "guest" makes it unclear that they are in-fact logged in as a guest.  If i am missing something, please explain.

**Comment by robnagler** [comment]
You are correct. This needs to be fixed. 

The fix is in the workflow of the GUI. The backend already supports what you want to accomplish.

My $.02. I think the GUI should warn the user when the try to logout as Guest and give them the option of converting to an authenticated user. 

There are other workflow issues. Once you've decided what workflows you'd like, we'll implement them.

**Comment by moellep** [comment]
Fixed with #1737

**Comment by pmessamer** [comment]
I think there is still an issue here.   If I go into Sirepo as a guest and
create simulations then click "Save Your Work", and  login under my
existing account: pmessamer@gmail.com,  the simulations I created as a
guest user are not visible in the account.

**Comment by moellep** [comment]
@messamer, this should be fixed now on alpha - give it a try.
