### ISSUE TITLE
can not connect to job supervisor

### ISSUE THREAD

**Issue by ahebnl** [radiasoft/sirepo#2771]
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: exclude_re=pykern.pkdebug.SECRETS_RE,
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkconfig.py", line 493, in to_environ
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: e = re.compile(exclude_re, flags=re.IGNORECASE)
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/re.py", line 234, in compile
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: return _compile(pattern, flags)
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/re.py", line 282, in _compile
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: "cannot process flags argument with a compiled pattern")
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: ValueError: cannot process flags argument with a compiled pattern
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: Exception was printed at:
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: ValueError: cannot process flags argument with a compiled pattern
> Aug 10 12:34:54 cpu-016.cs.nsls2.local sirepo_job_supervisor[34702]: File "/home/vagrant/.pyenv/versions/py3/bin/sirepo", line 8, in <module>
> 

 `exclude_re=pykern.pkdebug.SECRETS_RE` is already a compiled re with re.IGNORECASE, it got compiled again with re.IGNORECASE  in job.py

Is the pykern automatically updated while I am building nsls2 docker image ?

**Comment by robnagler** [comment]
You need the latest pykern:
```
cd ~/src/radiasoft/pykern
git pull
```

**Comment by ahebnl** [comment]
I cloned pykern repository on cpu016, still have this problem. also I find that pypi has the most recent version, so "pip install -r requirements.txt" in the docker building script should pick the pypi version (20200805 latest).

It is a pykern problem:

pydebug has:
SECRETS_RE = re.compile(r'(?:secret|otp\b|passw|private)', re.IGNORECASE), then used by sirepo job.py:

https://github.com/radiasoft/sirepo/blob/d321e42f99ed0d972ef48f0b0a3038b6bcb7fa88/sirepo/job.py#L171

passed back to pykern, compile with re.IGNORECASE again:

https://github.com/radiasoft/pykern/blob/9b68a5e6c3654f827826a6949219af2a447f4a02/pykern/pkconfig.py#L493

@ochubar

**Comment by robnagler** [comment]
I can see that the older version of pkconfig is getting executed. How is the docker image getting built?

**Comment by ahebnl** [comment]
I ran this script as vagrant:

https://github.com/ahebnl/sirepo/blob/master/etc/build-nsls2.sh

**Comment by robnagler** [comment]
I fixed the script with c8aedf5. It needs to uninstall pykern, too. pip install -r requirements.txt does not update pykern, it just checks that it is already installed. We have not build a new version of the docker image since that bug was fixed.

**Comment by ahebnl** [comment]
used this new script. problem not solved.
Maybe I was not clear in my first reply: the pykern needs a bugfix,

**Comment by robnagler** [comment]
I tested this on my VM. The pip uninstall wasn't working so it wasn't reinstalling pykern.

**Comment by robnagler** [comment]
@ahebnl please try the latest build-nsls2.sh https://github.com/radiasoft/sirepo/commit/4f0b0e8aefaf3600f558ba58f56cd4caae52f9aa

**Comment by ahebnl** [comment]
Thanks, it is working now.

Could not make `pip install -r requirements` work, maybe due to the proxy. But tried this method: https://docs.docker.com/network/proxy/, did not work. So I copied the pykern src and pip installed from this local copy

here is the new script [https://github.com/ahebnl/sirepo/commit/4fd8b88b3b95921d50e6b225c02a46c00da16a27]

@robnagler @ochubar

**Comment by robnagler** [comment]
I fixed up the script to pass the http_proxy (if it exists) and to install the local pykern in the build.

The proxy needs to be there if there are new requirements (in setup.py) that need to be pulled from the Internet.

I removed the `pip install -r requirements.txt` as the only reason for this is to install pykern.

Here's the latest: https://github.com/radiasoft/sirepo/commits/master
